#!/usr/bin/env bash
# Builds the scroll film from the three generated scenes (Higgsfield,
# Seedance 2.0, 1080p): 1 rotate+open, 2 pour, 3 spread on toast.
# usage: scripts/build-sequence.sh scene1.mp4 scene2.mp4 scene3.mp4
# Writes public/seq/d (16:9, 1600 px) and public/seq/m (3:4 portrait crop that
# follows the subject) and src/seq.ts with the frame count.
set -euo pipefail
cd "$(dirname "$0")/.."
[ $# -eq 3 ] || { echo "usage: $0 s1.mp4 s2.mp4 s3.mp4"; exit 1; }
rm -rf public/seq/d public/seq/m && mkdir -p public/seq/d public/seq/m

# Scenes 2 and 3 start on the previous scene's last frame: drop it.
JOIN="[0:v]setpts=PTS-STARTPTS[a];[1:v]trim=start_frame=1,setpts=PTS-STARTPTS[b];[2:v]trim=start_frame=1,setpts=PTS-STARTPTS[c];[a][b][c]concat=n=3:v=1:a=0,format=yuv420p,split=2[d][m]"
# Portrait crop centre (fraction of width) per global frame: tube on the
# right at the start, toast centre-left at the end.
F="if(lt(n,120),0.78-0.16*n/120,if(lt(n,240),0.62-0.06*(n-120)/120,0.56-0.12*min(n-240,120)/120))"
ffmpeg -v error -y -i "$1" -i "$2" -i "$3" -filter_complex "$JOIN;\
[d]scale=1600:900:flags=lanczos[dout];\
[m]crop=810:1080:x='max(0,min(iw-ow,($F)*iw-ow/2))':y=0,scale=720:960:flags=lanczos[mout]" \
  -map "[dout]" -c:v libwebp -quality 72 -compression_level 6 -start_number 1 public/seq/d/%04d.webp \
  -map "[mout]" -c:v libwebp -quality 70 -compression_level 6 -start_number 1 public/seq/m/%04d.webp

N=$(ls public/seq/d | wc -l)
S1=$(ffprobe -v error -count_frames -select_streams v:0 -show_entries stream=nb_read_frames -of csv=p=0 "$1")
S2=$(ffprobe -v error -count_frames -select_streams v:0 -show_entries stream=nb_read_frames -of csv=p=0 "$2")
cat > src/seq.ts <<TS
// Generated by scripts/build-sequence.sh — do not edit by hand.
export const SEQ = { count: $N, scenes: [$S1, $((S2 - 1)), $((N - S1 - S2 + 1))] };
TS
du -sh public/seq/d public/seq/m
echo "frames: $N"
