#!/usr/bin/env bash
# Builds the scroll film from the three generated scenes (Higgsfield,
# Seedance 2.0, 1080p 24 fps): 1 rotate+open, 2 pour, 3 spread on toast.
# usage: scripts/build-sequence.sh scene1.mp4 scene2.mp4 scene3.mp4
#
# Three tiers (the page picks one, see src/Film.tsx):
#   d  desktop   16:9  1600×900   every 2nd frame
#   m  phone     3:4    720×960   every 2nd frame, crop follows the subject
#   s  light     3:4    480×640   every 3rd frame (slow phones, data saver)
# Adjacent frames are cross-faded on the canvas, so 12 fps scrubs smoothly.
set -euo pipefail
cd "$(dirname "$0")/.."
[ $# -eq 3 ] || { echo "usage: $0 s1.mp4 s2.mp4 s3.mp4"; exit 1; }
rm -rf public/seq && mkdir -p public/seq/d public/seq/m public/seq/s

# Scenes 2 and 3 start on the previous scene's last frame: drop it.
JOIN="[0:v]setpts=PTS-STARTPTS[a];[1:v]trim=start_frame=1,setpts=PTS-STARTPTS[b];[2:v]trim=start_frame=1,setpts=PTS-STARTPTS[c];[a][b][c]concat=n=3:v=1:a=0,format=yuv420p,split=3[d][m][s]"
# Portrait crop centre (fraction of width) per source frame: tube on the
# right at the start, toast centre-left at the end.
F="if(lt(n,120),0.78-0.16*n/120,if(lt(n,240),0.62-0.06*(n-120)/120,0.56-0.12*min(n-240,120)/120))"
CROP="crop=810:1080:x='max(0,min(iw-ow,($F)*iw-ow/2))':y=0"
ffmpeg -v error -y -i "$1" -i "$2" -i "$3" -filter_complex "$JOIN;\
[d]select='not(mod(n,2))',scale=1600:900:flags=lanczos[dout];\
[m]${CROP},select='not(mod(n,2))',scale=720:960:flags=lanczos[mout];\
[s]${CROP},select='not(mod(n,3))',scale=480:640:flags=lanczos[sout]" \
  -map "[dout]" -fps_mode vfr -c:v libwebp -quality 74 -compression_level 6 -start_number 1 public/seq/d/%04d.webp \
  -map "[mout]" -fps_mode vfr -c:v libwebp -quality 72 -compression_level 6 -start_number 1 public/seq/m/%04d.webp \
  -map "[sout]" -fps_mode vfr -c:v libwebp -quality 66 -compression_level 6 -start_number 1 public/seq/s/%04d.webp

D=$(ls public/seq/d | wc -l); M=$(ls public/seq/m | wc -l); S=$(ls public/seq/s | wc -l)
cat > src/seq.ts <<TS
// Generated by scripts/build-sequence.sh — do not edit by hand.
export const SEQ = {
  d: { count: $D, w: 1600, h: 900 },
  m: { count: $M, w: 720, h: 960 },
  s: { count: $S, w: 480, h: 640 },
} as const;
export type Tier = keyof typeof SEQ;
TS
du -sh public/seq/*
echo "frames: d=$D m=$M s=$S"
