// Generated by scripts/build-sequence.sh — do not edit by hand.
export const SEQ = {
  d: { count: 181, w: 1600, h: 900 },
  m: { count: 181, w: 720, h: 960 },
  s: { count: 121, w: 480, h: 640 },
} as const;
export type Tier = keyof typeof SEQ;
